import { Stack } from '@mui/system';
import React, { useState, useEffect } from 'react'
import { Cards } from '../componenets'
import { Link } from 'react-router-dom';
import Footer from '../componenets/Footer';
import Navbar from '../componenets/Navbar';
import { FormField } from '../componenets';
import '../index.css'
const RenderCards = ({ data, title }) => {
    if (data && data.length > 0) {
        return data.slice(0, 12).map((ele) =>
            <Cards key={ele.id} {...ele} />
        )
    }
    else {
        return <h2 style={{ color: 'white' }}>{title}</h2>
    }
}



const Home = ({ data }) => {
    const [searchText, setSearchText] = useState('');
    const [cardsData, setCardsData] = useState([]);
    const [searchReslt, setSearchReslt] = useState(null);
    const [searchtimeOut, setSearchtimeOut] = useState(null);


    const handleText = (e) => {
        setSearchText(e.target.value)
        clearTimeout(searchtimeOut)


        setSearchtimeOut(
            setTimeout(() => {
                const serachRes = cardsData.filter((ele) => {
                    return ele.name.toLowerCase().includes(searchText.toLowerCase()) || ele.prompt.toLowerCase().includes(searchText.toLowerCase())
                })
                setSearchReslt(serachRes)
            }, 300)
        )

    }

    useEffect(() => {
        setCardsData(data);
    }, [data]);


    return (
        <>
            <div className='content'>
                <Navbar />
                <Stack p={2}>
                    <div className='headertext'>
                        <h1> The Dev-Community ShowCase</h1>
                        <p>Browse through the Collection <br /> of imaginative and visual Stunning Images generated by DEV-E AI.</p>
                    </div>
                    <FormField placeholder="Search Post" type='text' name='text' value={searchText} handleChange={handleText} />

                </Stack>
            </div>

            <div className='FORMFIELD'>

                <Stack direction={'row'} flexWrap={'wrap'} gap={3} justifyContent={'center'} >
                    {
                        searchText ? <RenderCards data={searchReslt} title="No Search Results Found" /> :
                            (<RenderCards data={cardsData} title="No post Found" />)
                    }
                </Stack>


                <Stack direction={'row-reverse'} justifyContent={'space-between'} flexWrap={'wrap'} p={3} alignItems={'center'} >

                    <img className='featureimg2' alt="dan momford style virtual world made by ai" data-src="https://static.fotor.com/app/features/img/aiimage/advance/dan momford style virtual world made by ai.jpg" data-ll-status="loaded" src="https://static.fotor.com/app/features/img/aiimage/advance/dan momford style virtual world made by ai.jpg" />
                    <div className='headertext'>
                        <h1>
                            AI Image Generator is the Future

                        </h1>

                        <p> Now it's AI period. <br /> Create amazing artwork by yourself <br /> using the power of Fotor's Artificial Intelligence image generator. <br /> Turn your imagination into paintings automatically. Try the best AI art generator now.</p>

                        <br />
                        <Link to={'/createPost'}>
                            <button className='but' style={{ padding: '12px 64px' }}><h3>Create Art</h3></button>

                        </Link>
                    </div>


                </Stack>


                <Stack direction={'row'} justifyContent={'space-between'} flexWrap={'wrap'} p={3} alignItems={'center'} >


                    <div className='headertext'>
                        <img className='featureimg2' data-src="https://static.fotor.com/app/features/img/aiimage/advance/a beautiful girl illustration style image created by ai art.jpg" alt="a beautiful girl illustration style image created by ai art" data-ll-status="loaded" src="https://static.fotor.com/app/features/img/aiimage/advance/a beautiful girl illustration style image created by ai art.jpg" />

                        <div>
                            <h1>
                                Not Only Text to Image AI, But Image to Image AI
                            </h1>
                            <p>With Fotor's AI art generator from text, you can create an image from a text description. Describe what you want, and watch the AI text to image generator online bring it to life in seconds. What's more, use the image you prefer to create a new picture with Fotor's AI image generator free. Our AI empowers anyone to create attractive AI paintings, illustrations, and various kinds of images.</p>
                            <br />
                            <Link to={'/createPost'}>
                                <button className='but' style={{ padding: '12px 64px' }}><h3>Generate</h3></button>

                            </Link>
                        </div>

                    </div>


                </Stack>

            </div>


<Footer/>
        </>
    )
}

export default Home